### ISSUE TITLE
[Image not working, not using docsify theme]

### ISSUE THREAD

**Issue by KendallDoesCoding** [neontuts/docsify-test#4]
I added a image, it's not loading, and not working within the docsify team, as you can see, here - https://deploy-preview-2--neontuts-docsify-test.netlify.app/_pages/journey-book.md

For [Pradumnasaraf](https://github.com/Pradumnasaraf) it worked, any ideas what the issue is @neontuts @vikasganiga05

**Comment by vikasganiga05** [comment]
I checked the #2 PR the image is added correctly. I suggested some changes to fix the broken link &rarr; https://github.com/neontuts/docsify-test/pull/2#pullrequestreview-1037669292
